export const colors = {
  MAIN_BACKGROUND: '#FFF',
  SECONDARY_BACKGROUND: '#D3DCE6',
  GRAY_BACKGROUND: '#F9FAFC',
  DISABLED_BACKGROUND: '#EAF3FF',
  DISABLED_TEXT: '#71B0FD',
  HEADERBTN_BACKGROUND: '#EFF2F7',
  PRIMARY_TEXT: '#002859',
  SPECIAL_TEXT: '#035AC5',
  SPECIAL_TEXT_SECONDARY: '#C0CCDA',
  SECONDARY_TEXT: '#647184',
  GRAYBORDER: '#E5E9F2'
}